### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ZCWei51** [nchen909/Pass-Tuning#1]
Hello!
When I run `scripts/run_gcn_tuning.sh graphcodebert  translate java-cs` , there was an error happened.
```
File "/Pass-Tuning/utils.py", line 627, in get_graph_metadata
    with open(filename, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Pass-Tuning/data_prefix/translate/prefix.txt.cs'
```
It seems to be caused by not being able to find the `prefix.txt.cs file`
In `File utils.py, line 627, function get_graph_metadata`, It has this note 
```python
def get_graph_metadata(args, tokenizer):
'''
    read prefix code from args.old_prefix_dir
    load to examples(raw code) and data(after encode to ids)
    GraphMetadata convert it to token_ids and distance_list
    return token_ids and distance_list for GAT init
'''
```
But I don't find any information about this file in README.MD or other files.
Could u please help me? Thanks!

**Comment by nchen909** [comment]
Thanks for your attention to my work! Here is the tar link of data_prefix: https://drive.google.com/file/d/1kKi47D-ab8K4d4ieNRlGUm3DeFSNlkay/view?usp=drive_link

**Comment by ZCWei51** [comment]
Thank you so much for your reply and help, your work has been very helpful, thanks again!!!

**Comment by ZCWei51** [comment]
> Thanks for your attention to my work! Here is the tar link of data_prefix: https://drive.google.com/file/d/1kKi47D-ab8K4d4ieNRlGUm3DeFSNlkay/view?usp=drive_link

This link seems to require permissions to access and has been requested from you, if you have a moment please go through it, thank you very much!

**Comment by nchen909** [comment]
I've already granted access permissions for the link. Please try accessing it again.

**Comment by ZCWei51** [comment]
> I've already granted access permissions for the link. Please try accessing it again.

I get the file, Thanks!
